---
- name: Create dotfiles directory
  ansible.builtin.file:
    path: "{{ dotfiles_dir }}"
    state: directory
    mode: '0755'

- name: Template .zshrc
  ansible.builtin.template:
    src: zshrc.j2
    dest: "{{ dotfiles_dir }}/.zshrc"
    mode: '0644'
  when: dotfiles_zshrc

- name: Symlink .zshrc
  ansible.builtin.file:
    src: "{{ dotfiles_dir }}/.zshrc"
    dest: "{{ home_dir }}/.zshrc"
    state: link
    force: true
  when: dotfiles_zshrc

- name: Template .gitconfig
  ansible.builtin.template:
    src: gitconfig.j2
    dest: "{{ dotfiles_dir }}/.gitconfig"
    mode: '0644'
  when: dotfiles_gitconfig

- name: Symlink .gitconfig
  ansible.builtin.file:
    src: "{{ dotfiles_dir }}/.gitconfig"
    dest: "{{ home_dir }}/.gitconfig"
    state: link
    force: true
  when: dotfiles_gitconfig

- name: Template .tmux.conf
  ansible.builtin.template:
    src: tmux.conf.j2
    dest: "{{ dotfiles_dir }}/.tmux.conf"
    mode: '0644'
  when: dotfiles_tmuxconf

- name: Symlink .tmux.conf
  ansible.builtin.file:
    src: "{{ dotfiles_dir }}/.tmux.conf"
    dest: "{{ home_dir }}/.tmux.conf"
    state: link
    force: true
  when: dotfiles_tmuxconf
